version: "3"

services:
  database:
    build: ./requirements/database
    container_name: container_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  backend:
    build: ./requirements/backend
    container_name: container_backend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database

  frontend:
    build: ./requirements/frontend
    container_name: container_frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - backend
